### ISSUE TITLE
Definir escopo

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#1]
- Quais algoritmos serão comparados

- Quais benchmarks serão utilizados

- Metodologia de análise

cc @miguelarauj1o e @pcstl

**Comment by JoaoGFarias** [comment]
- Objetivo:
  - [Symmetric traveling salesman problem](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/)
  - [Asymmetric traveling salesman problem](http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/)
  - [FHCP Challenge Set](http://www.flinders.edu.au/science_engineering/csem/research/programs/flinders-hamiltonian-cycle-project/fhcpcs.cfm)

- Algoritmos:

 1. [PSO](http://www.swarmintelligence.org/tutorials.php)
 2. [Multi-swarm Optimization](http://link.springer.com/chapter/10.1007/978-3-540-24653-4_50#page-1)
 3. [MCPSO](http://natcomp.liacs.nl/SWI/papers/Multi-swarm%20Optimization/MCPSO%20multi-swarm%20cooperative.pdf)
 4. [Genetic Algorithm + PSO](http://cogentoa.tandfonline.com/doi/abs/10.1080/23311835.2015.1048581)
 5. [Ant Colony](http://staff.washington.edu/paymana/swarm/stutzle99-eaecs.pdf)
 6. [Bee Colony](http://mf.erciyes.edu.tr/abc/pub/tr06_2005.pdf)
 7. [Bat algorithm](https://arxiv.org/pdf/1004.4170.pdf)

- Metodologia
  - Análise de performace
    - Número de gerações
    - Tempo de execução
    - Custo de memória
  - Análise de desenvolvimento
    - Dificuldade de implementação
    - Escolha de parâmetros

**Comment by miguelarauj1o** [comment]
Critérios de parada:

- caso seja excedido o número máximo de gerações permitidas (**200.000 gerações**)
- caso o fitness do melhor indivíduo dentre as últimas 500 gerações tenha variado em menos de um threshould estabelecido (**sigma 10^5**)

**Comment by JoaoGFarias** [comment]
> caso seja excedido o número máximo de gerações permitidas (200.000 gerações)
@miguelarauj1o Estou achando o número de gerações muito grande. No PSO que implementei, com 500 indivíduos, o algoritmo terminava com menos de 100. 
Porque colocasse esse valor?

**Comment by miguelarauj1o** [comment]
isso é um critério de parada. Isso corta aqueles momentos que fica pra sempre num ponto que não é o final. É um teto, podemos diminuir, se assim a maioria preferir.

**Comment by JoaoGFarias** [comment]
Estuda melhor essa questão em #7 

Então, fechando:

- Objetivo:
   - Resolver o ATSP, usando com benchmarking os dados da TSPLib
- Algoritmos:
   - PSO ( #3 )
   - MCPSO ( #6 )
   - Ant Colony ( #4 )
   - Bacterial Foraging ( #5 )
- Metodologia: #7 

Fechou?
