### ISSUE TITLE
[Resultados] Criar GUI para exibição live da execução

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#10]
Requisitos

- Escolher qual algoritmo usar;
- Escolher número de nós ou instância do problema;
- Escolher parametros do algoritmo.

**Comment by miguelarauj1o** [comment]
Eu acho que apresentar os gráficos e tabelas dos resultados é suficiente.
O que vocês acham @pcstl e @JoaoGFarias

**Comment by JoaoGFarias** [comment]
Naturalmente, a GUI é vem após conseguirmos produzir os gráficos e tabelas. Não tem problema deixarmos a issue aberta e assinalada aqui; adicionamos a GUI no escopo se der tempo.

**Comment by miguelarauj1o** [comment]
http://pandas.pydata.org/

**Comment by pcstl** [comment]
No caso, a parte de produzir gráficos/tabelas estaria incluída neste issue ou seria responsabilidade de cada um? Eu acho que é melhor se unificarmos como os gráficos/tabelas serão gerados

**Comment by JoaoGFarias** [comment]
Will not be attemped
