### ISSUE TITLE
Definir roadmap

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#2]
Depende de #1

**Comment by miguelarauj1o** [comment]
@JoaoGFarias, fechei a issue #1. Podemos avançar aqui.

**Comment by JoaoGFarias** [comment]
![xgh-e1330433625262](https://cloud.githubusercontent.com/assets/1585655/16365569/522750ba-3bda-11e6-9846-63e1d33d2350.jpg)

E depois refatoramos tudo com
![download](https://cloud.githubusercontent.com/assets/1585655/16365570/5b1efc18-3bda-11e6-909e-2ea5e606d0e2.jpeg)
Como sei que @pcstl concorda, vou fechar essa issue.
