### ISSUE TITLE
[Algoritmo] Implementar MCPSO

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#6]
Pasta src/multiPSO

**Comment by miguelarauj1o** [comment]
http://natcomp.liacs.nl/SWI/papers/Multi-swarm%20Optimization/MCPSO%20multi-swarm%20cooperative.pdf

**Comment by JoaoGFarias** [comment]
Qual o status aqui @miguelarauj1o ?

**Comment by miguelarauj1o** [comment]
trabalhando
