### ISSUE TITLE
[Análise] Determinar metodologia de análise

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#7]
- [x] Conseguir slides (guardá-los na pasta doc/referencia)
- [x] Analisar papers de comparação
    - [x] [A comparison of swarm intelligence algorithms for structural engineering optimization](http://onlinelibrary.wiley.com/doi/10.1002/nme.4295/abstract)
- [x] Criar documento com processo de análise na pasta doc/referencia

**Comment by JoaoGFarias** [comment]
Acho válido dar uma olhada no [OptimizationBenchmarking.org](http://optimizationbenchmarking.github.io/)

Aqui tem slides explicando a ferramenta: https://circle-artifacts.com/gh/optimizationBenchmarking/documentation-intro-slides/50/artifacts/0/tmp/circle-artifacts.aXWSHRd/intro-slides.pdf

**Comment by JoaoGFarias** [comment]
E, num quesito mais teórico, isso pode ser interessante: http://www.sciencedirect.com/science/article/pii/S2210650211000034

**Comment by JoaoGFarias** [comment]
Diga suas dores @miguelarauj1o

**Comment by miguelarauj1o** [comment]
Não cheguei aqui ainda. Estou terminando o algoritmo. Tive que adiantar outras coisas.

**Comment by JoaoGFarias** [comment]
Acho mais importante tu focar logo nisso, pois já desbloquea #8.
Depois posso te ajudar com #13; fiz umas pesquisas aqui e acho que posso tunar #3 ainda um pouco.
