### ISSUE TITLE
[Resultados] Criar código de suporte para análise

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#8]
Pasta destino do código: doc/src

Obs: Sincronizar com #7

**Comment by pcstl** [comment]
No caso, o que o código de suporte precisa fazer exatamente? Acho que não entendi muito bem

**Comment by JoaoGFarias** [comment]
É o código para automatizar o processo de análise e geração de gráficos. Um script que pegue os dados de um lugar especificado e gere as coisas de uma forma organizada :)

**Comment by pcstl** [comment]
Massa, tranquilo. Vou fazer um código bem genérico pra gerar gráficos e depois a gente discute o que especificamente vale a pena gerar.
