### ISSUE TITLE
[Modelagem] Modelar problema do TSP assimétrico

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/comparing_swarm_intelligence#9]
- [x] Estudar como usar os algoritmos para resolver o problema do TSP assimétrico.
- [x] Modelar benchmark do TSP assimétrico da TSPLIB.

**Comment by JoaoGFarias** [comment]
Material interessante [aqui](http://ijcsi.org/papers/IJCSI-9-6-2-264-271.pdf) e [aqui](http://www.exatas.ufpr.br/portal/docs_degraf/paulo/TravellingSalesmanProblem.pdf)

**Comment by miguelarauj1o** [comment]
@JoaoGFarias, vou me basear somente no primeiro link. O segundo contém mais de 200 págs.

**Comment by miguelarauj1o** [comment]
Estou fechando porque @pcstl já resolveu em #17.
